### ISSUE TITLE
Project is unusable in 3.1.0

### ISSUE THREAD

**Issue by LifeIsStrange** [mihneadb/node-directory-tree#105]
``` Javascript
const dirTree = require("directory-tree");
const tree = dirTree("/");
```

``` Typescript
/home/stephane/dev/freelance/JardinerieApp/jardinerieApp/node_modules/directory-tree/lib/directory-tree.js:52
  if (options.depth !== undefined && options.attributes.indexOf('size') !== -1) {
              ^

TypeError: Cannot read property 'depth' of undefined
    at directoryTree (/home/stephane/dev/freelance/JardinerieApp/jardinerieApp/node_modules/directory-tree/lib/directory-tree.js:52:15)
    at Object.<anonymous> (/home/stephane/dev/freelance/JardinerieApp/jardinerieApp/html_content_parser/getFilesystemTreeOfFolder.js:2:14)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)

```

using node v15.5.1

note that const tree = dirTree("/"); or "/src" or "../src" (the latter being the most logical since the file is nested in a folder) all of those path result in the same depth error..

@mihneadb this project seems very useful, I would like to make it work plz

**Comment by LifeIsStrange** [comment]
using directory-tree@3.1.0

**Comment by LifeIsStrange** [comment]
I confirm that the project is working well with the @3.0.1 !

**Comment by mihneadb** [comment]
@LifeIsStrange hey, can you please provide a more specific example - what tree structure are you working iwth and what is happening? I'm confused between the "/" and "../src" call. Thanks

**Comment by LifeIsStrange** [comment]
I simply have a root project that contains a package.json, an src folder and an HTMLParser folder.

I execute node parser.js inside the HTMLParser folder.
This script contains the basic code shown above that it throw the error shown above for any path I tried.
In the older version, ("../src") show the correct tree instead of throwing an error.

**Comment by LetsMelon** [comment]
I had the same error `if (options.depth !== undefined && options.attributes.indexOf('size') !== -1) {` and I think it's because the check if `options` is `undefined` is after the check if `options.depth` isn't undefined.

https://github.com/mihneadb/node-directory-tree/blob/305dcd368b94e904dd28f9f06413b3b74e21dadf/lib/directory-tree.js#L52

and 

https://github.com/mihneadb/node-directory-tree/blob/305dcd368b94e904dd28f9f06413b3b74e21dadf/lib/directory-tree.js#L57

So a fix should be place the check from line 57 before the if statement from line 52. (Haven't tested it myself though.)

**Comment by mihneadb** [comment]
@LetsMelon indeed, you are right. Added a fix + a test. Thanks!
@LifeIsStrange thanks for reporting, pls try with 3.1.1.

**Comment by LifeIsStrange** [comment]
I'll try again next week 👍 Thanks for making this library :)

**Comment by LetsMelon** [comment]
Glad, that i could help
